/// <reference lib="dom" />
// Auto-generated by scripts/sign-default-pack.ts. Do not edit manually.
import type { PackManifest } from "./effect-packs";

const ASSET_BASE64: Record<string, string> = {
  "jump-scare-1": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip18AAAAASUVORK5CYII=",
  "jump-scare-2": "R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
  "jump-scare-3": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==",
  "jump-scare-audio": "UklGRiUAAABXQVZFZm10IBAAAAABAAEARKwAAESsAAABAAgAZGF0YQEAAACA"
};

function base64ToBytes(base64: string): Uint8Array {
  const binary = atob(base64);
  return Uint8Array.from(binary, (c) => c.charCodeAt(0));
}

export const defaultPackAssets: Record<string, Uint8Array> = {
  "jump-scare-1": base64ToBytes(ASSET_BASE64["jump-scare-1"]),
  "jump-scare-2": base64ToBytes(ASSET_BASE64["jump-scare-2"]),
  "jump-scare-3": base64ToBytes(ASSET_BASE64["jump-scare-3"]),
  "jump-scare-audio": base64ToBytes(ASSET_BASE64["jump-scare-audio"]),
};

export const defaultPackManifest = {
  "id": "startip.default",
  "version": "1.0.0",
  "effects": {
    "jump-scare": {
      "id": "jump-scare",
      "name": "Jump Scare",
      "type": "jump-scare",
      "assetIds": [
        "jump-scare-1",
        "jump-scare-2",
        "jump-scare-3"
      ],
      "audioId": "jump-scare-audio",
      "maxDisplayPct": 80
    },
    "screen-flash": {
      "id": "screen-flash",
      "name": "Screen Flash",
      "type": "screen-flash",
      "durationMs": 1000
    },
    "screen-cover": {
      "id": "screen-cover",
      "name": "Screen Cover",
      "type": "screen-cover",
      "durationMs": 3000,
      "obscuredPct": 70
    },
    "tunnel-vision": {
      "id": "tunnel-vision",
      "name": "Tunnel Vision",
      "type": "tunnel-vision",
      "durationMs": 5000,
      "visibleDiameterPct": 35
    }
  },
  "assets": {
    "jump-scare-1": {
      "id": "jump-scare-1",
      "type": "image",
      "path": "default-pack/jump-scare/1.png",
      "hash": "23128c6f48002b4e0e04b268cd3e9568485555717164558b86776bd46a035328",
      "contentType": "image/png"
    },
    "jump-scare-2": {
      "id": "jump-scare-2",
      "type": "gif",
      "path": "default-pack/jump-scare/2.gif",
      "hash": "ef1955ae757c8b966c83248350331bd3a30f658ced11f387f8ebf05ab3368629",
      "contentType": "image/gif"
    },
    "jump-scare-3": {
      "id": "jump-scare-3",
      "type": "image",
      "path": "default-pack/jump-scare/3.png",
      "hash": "c414cd0e204de974f73753c7e28d7638e7b3691bb8b1a2bab6b25bb7fed7ce77",
      "contentType": "image/png"
    },
    "jump-scare-audio": {
      "id": "jump-scare-audio",
      "type": "audio",
      "path": "default-pack/jump-scare/audio.wav",
      "hash": "b252c340524340648bd30bb1a54705afb15f8158ed92fe869fee596e72a2d164",
      "contentType": "audio/wav"
    }
  },
  "publicKey": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFzBu7RJuuum79xTN7eqx6sUUjC05j0i478+bYiiq9rsdaGJJAVh5EcVhP/UMT9V2fM0voHKtBrPoY1sBk6onEQ==",
  "manifestHash": "5ef0d0fe195747bb4553e6c2975ac0ca4f89e83ae5c8ac89b76d1420b84e6938",
  "signature": "psUoUEGj0u0JUfYg3SO8yGHXs/KcRXVxJWMNZUT/puXSDjZSaIISfYT/pmu9mEIB0YLuK0qy1OcLkhv5pHlYZg=="
} as unknown as PackManifest;
