-- Add overlay_id to profiles.
--
-- The overlay_id is an opaque, unguessable token that addresses the private
-- OBS browser source. It is generated automatically when onboarding completes
-- (onchain_registered = true) and can be regenerated by the creator from the
-- dashboard.
--
-- Public read is never exposed; the public_profiles view deliberately omits
-- this column. The authenticated owner can read it because the owner SELECT
-- policy is on the base table.
--
-- A plain UNIQUE constraint on a nullable column allows multiple NULLs, so
-- only one non-null overlay_id value can exist per profile.

alter table public.profiles add column if not exists overlay_id text unique;

-- Backfill existing on-chain registered creators with a fresh overlay_id.
update public.profiles
  set overlay_id = replace(gen_random_uuid()::text, '-', '')
  where onchain_registered = true
    and overlay_id is null;
